version: '3'

services:
  koel:
    image: phanan/koel
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=overtly-impeccable-octopus.data-1.use1.tembo.io
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=CQzDedvI89HdBJtM
      - DB_DATABASE=koel
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes

  database:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CQzDedvI89HdBJtM

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
